image:
  file: .gitpod.Dockerfile
tasks:
  - before: install -o gitpod -g gitpod .gp/.bash_aliases /home/gitpod
  - init: |
      export DDEV_NONINTERACTIVE=true
      bash .gp/init.sh
    command: echo 'start script'

ports:
  # Direct-connect ddev-webserver port that is the main port
  - port: 8080
    visibility: private
  # Currently un-notified and unsupported mailhog http port
  - port: 8025
    onOpen: ignore
    visibility: private
  # Currently un-notified and unsupported mailhog https port
  - port: 8026
    onOpen: ignore
    visibility: private
  # Currently un-notified and unsupported phpmyadmin http port
  - port: 8036
    onOpen: ignore
    visibility: private
  # Currently un-notified and unsupported phpmyadmin https port
  - port: 8037
    onOpen: ignore
    visibility: private
  # router http port that we're ignoring.
  - port: 8888
    onOpen: ignore
    visibility: private
  # router https port that we're ignoring.
  - port: 8889
    onOpen: ignore
    visibility: private
  # xdebug port
  - port: 9000
    onOpen: ignore
    visibility: private
  # projector port
  - port: 9999
    visibility: private